global:
  USER_NAME:
  USER_PASSWORD:

pdf:
  pdf_switch: 0
  pdf_password: None

download:
  is_detail: True
  thread_number: 5
  remove_favorites: True
  out_time_day: 30
  key_world : "萝莉,蘿莉"
  filter : "CG雜圖,生肉,耽美花園,偽娘哲學,禁書目錄,英語 ENG,耽美花園,重口地帶,歐美,WEBTOON"
  page : 2
  download_plan : 3



