name: 运行Python脚本  # 工作流名称
on:
  push:  # 触发条件：代码推送时运行
    branches: [master]  # 目标分支
  schedule:
    - cron: '10 23 * * *'  # 北京时间每天上午7点10分运行（UTC+8 → 23+8=次日7:10）
  workflow_dispatch:  # 允许手动触发
jobs:
  run-script:
    runs-on: ubuntu-latest  # 运行环境
    permissions:
      contents: write  # 允许提交代码到仓库
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4  # 检出仓库代码
      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 指定与脚本兼容的Python版本
          cache: 'pip'
      - name: 安装依赖库
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 安装依赖
      - name: 执行Python脚本
        env:
          USER_NAME: ${{secrets.USER_NAME}}
          USER_PASSWORD: ${{secrets.USER_PASSWORD}}
        run: python ./src/main.py
      - name: 上传爬虫结果
        uses: actions/upload-artifact@v4
        with:
          name: comic  # 工件名称
          path: ./comics/      # 要上传的目录/文件
          retention-days: 90   # 保留天数1-90
          if-no-files-found: warn  # 无文件时仅警告不失败
      - name: 提交配置到Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add ./data/ || echo "data目录无文件可添加"
          git add ./logs/ || echo "logs目录无文件可添加"
          git commit -m "Add data or logs $(date +'%Y-%m-%d_%H-%M-%S')" || echo "无新日志需提交"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}